trigger:
  none

variables:
  # Docker Registry
  dockerRegistry: 'ashudevops'
  imageName: 'ashu290996/wonderlust'
  imageTag: '$(Build.BuildId)'
  
  # SonarQube
  sonarQubeServiceConnection: 'sonarQube'
  sonarProjectKey: 'wonderlust'
  
  # Kubernetes
  kubernetesServiceConnection: 'k8s-prod-connection'
  stagingNamespace: 'staging'
  productionNamespace: 'production'
  
  # Build
  #vmImageName: 'ubuntu-latest'
  
  # Security Thresholds
  trivySeverity: 'HIGH,CRITICAL'
  owaspFailOnCVSS: 7

pool:
 name: default

stages:
    - stage: Compile
      displayName: 'Compile of the code'
      jobs:
        - job: Installdependency
          displayName: 'Installdependency for the code'
          steps:
          - task: NodeTool@0
            inputs:
             versionSource: 'spec'
             versionSpec: '21.x'

          - script: npm install
            displayName: Installdependency backend
            workingDirectory: wanderlust-3tier-project/backend
            continueOnError: true

          - script: npm install
            displayName: Installdependency frontend
            workingDirectory: wanderlust-3tier-project/frontend
      
    - stage: SonarQube
      displayName: 'SonarQube Analysis'
      jobs:
          - job: SonarQubeAnalysis
            steps: 

            - task: SonarQubePrepare@8
              displayName: 'Prepare SonarQube Analysis'
              inputs:
                SonarQube: '$(sonarQubeServiceConnection)'
                scannerMode: 'CLI'
                configMode: 'manual'
                cliProjectKey: 'blog-app'
                cliProjectName: 'blog-app'
                cliSources: 'wanderlust-3tier-project'
                  
            - task: SonarQubeAnalyze@8
              displayName: 'SonarQubeAnalyze'
              inputs:
                jdkversion: 'JAVA_HOME_21_X64'

            - task: SonarQubePublish@8
              displayName: 'SonarQubePublish'
              continueOnError: false
              inputs:
                pollingTimeoutSec: '300'
                
    - stage: OWASP
      jobs:
        - job: OWASP
          displayName: 'OWASP dependency checker'
          steps:

            - task: dependency-check-build-task@6
              continueOnError: true
              inputs:
                projectName: 'wonderlust-3tier'
                scanPath: 'wanderlust-3tier-project'
                format: 'HTML'
                uploadReports: true
                failOnCVSS: '7'

    - stage: Trivyscan
      jobs:
        - job: Trivyfilescan
          displayName: 'Trivyfilescan'
          steps:
            - script: trivy fs . --severity $(trivySeverity) --format table --output $(Build.ArtifactStagingDirectory)/trivy-fs-backend-report.txt
              workingDirectory: wanderlust-3tier-project/backend

            - script: echo cat $(Build.ArtifactStagingDirectory)/trivy-fs-backend-report.txt
              workingDirectory: wanderlust-3tier-project/backend

            - script: trivy fs . --severity $(trivySeverity) --format table --output $(Build.ArtifactStagingDirectory)/trivy-fs-frontend-report.txt
              workingDirectory: wanderlust-3tier-project/frontend

            - script: echo cat $(Build.ArtifactStagingDirectory)/trivy-fs-frontend-report.txt
              workingDirectory: wanderlust-3tier-project/frontend  




