trigger:
  none

variables:
  # Docker Registry
  dockerRegistry: 'ashudevops'
  imageName: 'ashu290996/wonderlust'
  imageTag: '$(Build.BuildId)'
  
  # SonarQube
  sonarQubeServiceConnection: 'SonarQube'
  sonarProjectKey: 'wonderlust'
  
  # Kubernetes
  kubernetesServiceConnection: 'k8s-prod-connection'
  stagingNamespace: 'staging'
  productionNamespace: 'production'
  
  # Build
  #vmImageName: 'ubuntu-latest'
  
  # Security Thresholds
  trivySeverity: 'HIGH,CRITICAL'
  owaspFailOnCVSS: 7

pool:
 name: default

stages:
    - stage: Compile
      displayName: 'Compile of the code'
      jobs:
        - job: CompilebackedJob
          displayName: 'Compiling the backend code'
          steps:
              - script: |
                 echo "Compiling backend"
                 cd wanderlust-3tier-project/backend
                 find . -name "*.js" -exec node --check {} +
        - job: CompilefrontendJob
          displayName: 'Compiling the fronted code'
          steps:
              - script: |
                 echo "Compiling fronted"
                 cd wanderlust-3tier-project/fronted
                 find . -name "*.js" -exec node --check {} +

